### ISSUE TITLE
JAVA_HOME setting cannot change

### ISSUE THREAD

**Issue by panosgeorgak** [wso2/devstudio-tooling-platform#4]
The user cannot change the JAVA_HOME variable which seems to be hard-coded as /home/saminda/software/jdk1.6.0_20 
As a result the carbon server in debian 8.6.0 linux distribution can only be started from command line and not through eclipse creating deployment problems
![screenshot from 2016-11-15 16 15 37](https://cloud.githubusercontent.com/assets/11481059/20338415/a7553e06-abdf-11e6-80c9-79479be06c28.png)
.

**Comment by sohaniwso2** [comment]
moved to https://github.com/wso2/devstudio-tooling-ei/issues/67. hence closing this issue
